### ISSUE TITLE
JsonPatchOperationBeta does not support boolean

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/typescript-sdk#18]
Starting version 1.3.0, `JsonPatchOperationBeta` is using `JsonPatchOperationValueBeta` as value.
`JsonPatchOperationValueBeta` is defined as follow, which means that boolean are not authorized:
```
export type JsonPatchOperationValueBeta = Array<ArrayInnerBeta> | number | object | string;
```

It was before and we should be able to patch a boolean property.

**Comment by tyler-mairose-sp** [comment]
Hey @yannick-beot-sp, this was fixed in https://github.com/sailpoint-oss/typescript-sdk/commit/f53f4e4708b3697ca7c273a6050191e45de9848f and released in https://github.com/sailpoint-oss/typescript-sdk/releases/tag/v1.3.4
