### ISSUE TITLE
CORS preflight error when running in the browser

### ISSUE THREAD

**Issue by wcarson** [sailpoint-oss/typescript-sdk#2]
I was trying to update a simple VueJS web app I developed to use the TS SDK instead of a custom API client. When using the TS SDK I'm getting CORS errors when using the custom client (which also uses Axios) I don't.

The only difference I could see in the requests were:

1. The custom Axios client executed a normal GET request where the TS SDK did a GET+Preflight
2. The custom Axios client had some CORS-related request headers that the TS SDK's requests didn't: 

    - `origin = https://mysite.com`
    - `sec-fetch-mode = cors`
    - `sec-fetch-site = cross-site`

**Comment by philip-ellis-sp** [comment]
When using the SDK or making any API calls from a web browser to a different domain, you will get a CORS error unless the host has CORS configured for the calling domain. I don't think this is a bug in the SDK, but an implementation issue. You need to adjust the app to call the same domain and route requests through a server.
