### ISSUE TITLE
Regression when creating Configuration

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/typescript-sdk#30]
The SDK is now posting credentials
```
this.clientId = param.clientId;
this.clientSecret = param.clientSecret;
var url = "".concat(this.tokenUrl);
var formData = new form_data_1.default();
formData.append('grant_type', 'client_credentials');
formData.append('client_id', this.clientId);
formData.append('client_secret', this.clientSecret);
if (!this.accessToken) {
    this.accessToken = this.getAccessToken(url, formData);
}
```

However, if `clientId` is undefined (because passing directly the access token to the configuration), the line `formData.append('client_id', this.clientId);` fails

Not passing any clientId or clientSecret used to work.
Preparing the `formData` should be done in the `if (!this.accessToken)`

**Comment by darrell-thobe-sp** [comment]
This issue should have been resolved with this commit. https://github.com/sailpoint-oss/typescript-sdk/commit/bdf99b51e24eea954333b51d08d1717c5af18073
